### ISSUE TITLE
VSCode explorer commands missing

### ISSUE THREAD

**Issue by nwoodfnts** [demisto/vscode-extension#22] opened 2021-09-03 15:30 UTC
VSCode explorer commands missing when using right click. Per extension readme it should be available to run commands from right click context.

**Comment by Itay4** [comment] 2021-09-05 10:36
hi @nwoodfnts, thanks for reporting this !
are you referring to those commands?
<img width="614" alt="Screen Shot 2021-09-05 at 13 34 28" src="https://user-images.githubusercontent.com/31018228/132123740-510249c3-bc46-4f36-86d1-675b6ee487aa.png">

**Comment by Itay4** [comment] 2021-09-07 17:20
the right-click commands were added in version 0.0.4 and are limited to files in the workspace in the Packs/* directory - can you please confirm this is the case?
if so, can you provide more details about your env?

**Comment by nwoodfnts** [comment] 2021-09-09 13:07
It may be due to it not being in a Packs/* directory. When I setup dev/prod GitHub it didn't create directories for packs etc. Its all individual files.

**Comment by Itay4** [comment] 2021-09-28 16:42
@nwoodfnts sorry for the late reply

this seems to be the expected behavior

can you please elaborate on the structue of your workspace so we can see what we can do to support it?

**Comment by nwoodfnts** [comment] 2021-09-28 19:09
![image](https://user-images.githubusercontent.com/82391478/135150383-70217391-8a7b-4d0c-b75b-64ccf881f9c7.png)

it uses prefixes instead of folders - see attached screen shot as well as one above.

**Comment by jochman** [comment] 2021-09-29 09:08
fixed in 0.0.5.

**Closed by jochman** 2021-09-29 09:08 UTC
